sudo: required

language: node_js

node_js:
- "8"

services:
- docker

before_install:
- docker build -t rkydx/docker-react -f Dockerfile.dev .

script:
- docker run rkydx/docker-react npm run test -- --coverage
